// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByWS9qa6FhB3HCceN0y7JJBypNEbP5UHQ',
    appId: '1:714733312376:web:cd0e19d5207f32ff1b908d',
    messagingSenderId: '714733312376',
    projectId: 'babyshop-3eb11',
    authDomain: 'babyshop-3eb11.firebaseapp.com',
    storageBucket: 'babyshop-3eb11.appspot.com',
    measurementId: 'G-9K1PJPETMW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApvTrfnz36Q6T5M74lSkC9HGC5sQu_0_I',
    appId: '1:714733312376:android:c1539badfa22d3971b908d',
    messagingSenderId: '714733312376',
    projectId: 'babyshop-3eb11',
    storageBucket: 'babyshop-3eb11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqU4fu8zIWfHsyqL0P257luNsQQSeMCkQ',
    appId: '1:714733312376:ios:6c5bdd61fcdd874a1b908d',
    messagingSenderId: '714733312376',
    projectId: 'babyshop-3eb11',
    storageBucket: 'babyshop-3eb11.appspot.com',
    iosBundleId: 'com.example.adminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqU4fu8zIWfHsyqL0P257luNsQQSeMCkQ',
    appId: '1:714733312376:ios:6c5bdd61fcdd874a1b908d',
    messagingSenderId: '714733312376',
    projectId: 'babyshop-3eb11',
    storageBucket: 'babyshop-3eb11.appspot.com',
    iosBundleId: 'com.example.adminPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKlKSJoeh6FV-6dRICHFbPrNaALht4Gys',
    appId: '1:714733312376:web:33704b64c7c6d8141b908d',
    messagingSenderId: '714733312376',
    projectId: 'babyshop-3eb11',
    authDomain: 'babyshop-3eb11.firebaseapp.com',
    storageBucket: 'babyshop-3eb11.appspot.com',
    measurementId: 'G-2928VERHMM',
  );
}
